import { getAsset } from "../../config";

export const events = [
  {
    "title": "SITUATIONAL QUE",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/situational que.webp"),
    "description": "About the event:\n Situational Que(How a candidate thinks,prioritizes,and reacts) \n\nPool Prize:\nRs 6000/-\n\nParticipation certificates will be given to all participants.\n\nEvent Coordinator:\nDr Sonia\nDr.Vishal Saxena,Saguna\n Dilipkumar  Samanta  \n Shivani Bhardwaj\n Dr.Manoj Pathak,",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "BRAIN QUEST",
    "subtitle": "TECHNICAL",
    "icon": "Brain",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/brain quest.webp"),
    "description": "About the event:\nA test of knowledge, exclusively in Mechanical Engineering discipline as a competition between Individuals and Teams as a form of awareness...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "TECHNICAL POSTER MAKING",
    "subtitle": "TECHNICAL",
    "icon": "Paintbrush",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/postermaking.webp"),
    "description": "About the event:\n1. Participant will make a poster on 'Electrical Engineering' theme...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "ELECTRO QUIZZERS",
    "subtitle": "TECHNICAL",
    "icon": "Zap",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/electroquizzer.webp"),
    "description": "About the event:\n\nThis event focuses on building practical skills by working on real-world datasets...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "CAD DARSHAN",
    "subtitle": "TECHNICAL",
    "icon": "Box",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/cad darshan.webp"),
    "description": "About the event:\n\nThe event here explores the understanding of AutoCAD...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "TECH PROBE",
    "subtitle": "TECHNICAL",
    "icon": "Radar",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/tech probe.webp"),
    "description": "Tech-probe is a fun quiz event happening at Renaissance 2026...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "PUZZLE MANIA",
    "subtitle": "TECHNICAL",
    "icon": "Puzzle",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/puzzle mania.webp"),
    "description": "About the event:\nPuzzle Mania is a series of exciting puzzle games...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "PROGRAMMER'S PLAYGROUND",
    "subtitle": "TECHNICAL",
    "icon": "Code",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/programmer playground.webp"),
    "description": "About the event:\nA coding competition designed to test programming skills...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "BEST OUT OF WASTE",
    "subtitle": "TECHNICAL",
    "icon": "Recycle",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/best out of waste.webp"),
    "description": "About the event:\nThe event here explores the creativity and understanding of the waste management...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "SCREENFLEX",
    "subtitle": "TECHNICAL",
    "icon": "Blocks",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/screen flex event.webp"),
    "description": "About the event:\nJoin us for ScreenFlex, an exciting hands-on workshop...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "FILM FLICK(SHORT FILM)",
    "subtitle": "TECHNICAL",
    "icon": "Zap",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/flick.webp"),
    "description": "About the event:\nThis is a event of making short film...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "HARDWARE BITES",
    "subtitle": "TECHNICAL",
    "icon": "Cpu",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/hardware.webp"),
    "description": "About the event:\nThis is hardwate assembling and troubleshooting event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "DEXTERITY ",
    "subtitle": "TECHNICAL",
    "icon": "Move",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/dexterity.webp"),
    "description": "About the event:\nThe event here explores the creativity of participant...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1 "
  },
  {
    "title": "3D MANIA",
    "subtitle": "TECHNICAL",
    "icon": "Box",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/3d mania.webp"),
    "description": "About the event:\nParticipants will design a 3D object using AutoCAD...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "RESINOCLOCK",
    "subtitle": "TECHNICAL",
    "icon": "Clock",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/resin oclock.webp"),
    "description": "About the event:\nResin art is the practice of using epoxy resin in artwork...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "TECH HUNT",
    "subtitle": "TECHNICAL",
    "icon": "Search",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/tech hunt.webp"),
    "description": "About the event:\n1. Tech-Charades (Dumb Charades with a Twist)...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "TECHNOCRAZY",
    "subtitle": "TECHNICAL",
    "icon": "Zap",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/technocrazy.webp"),
    "description": "About the event:\nA technical event where students showcase innovative projects...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "TECH SPECTRUM",
    "subtitle": "TECHNICAL",
    "icon": "Atom",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/tech spectrum.webp"),
    "description": "About the event:\nRound 1: Guess the Brand, Boss, and Beat...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technicaL",
    "day": "day3"
  },
  {
    "title": "ROBO SOCCER",
    "subtitle": "TECHNICAL",
    "icon": "Bot",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/robo-soccer.webp"),
    "description": "About the event:\nRoboSoccer is an exciting robotics event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "GAME OF DRONES",
    "subtitle": "TECHNICAL",
    "icon": "Navigation",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/game of drones.webp"),
    "description": "About the event:\nParticipants design and fly a wireless remotecontrolled drone...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "SUBITO",
    "subtitle": "TECHNICAL",
    "icon": "Zap",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/subito.webp"),
    "description": "About the event:\nSubito is a fastpaced and thrilling event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "KNOWLEDGE KNOCKOUT",
    "subtitle": "TECHNICAL",
    "icon": "Box",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/knowledge knockout.webp"),
    "description": "About the Event:\n\n Knowledge Knockout is a technical quiz based event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "DSA BATTLEGROUND",
    "subtitle": "TECHNICAL",
    "icon": "Brain",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/dsa battleground.webp"),
    "description": "About the Event:\n\nDSA On is a simple basic programming contest...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "SLOWEST ROLLER COASTER ",
    "subtitle": "TECHNICAL",
    "icon": "Blocks",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/roller coaster.webp"),
    "description": "About the Event:\n\nPreparing roller coaster from paper on which ball will slip slowly...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "CREATIVE PIXEL",
    "subtitle": "TECHNICAL",
    "icon": "Zap",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/creative pixels.webp"),
    "description": "About the Event:\n\nCreative Pixels is an exciting and engaging event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "ROBO WAR ",
    "subtitle": "TECHNICAL",
    "icon": "Bot",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/robo-war.webp"),
    "description": "About the Event:\n\n'Tug of War' is a thrilling robotics competition...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "NATIONAL PROJECT EXPO",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/national project.webp"),
    "description": "About the event:\n event that tests participants' ability to think and react...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "BATTLE OF BRAINS",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/battle of brains.webp"),
    "description": "About the event:\n event that tests participants' ability to think and react...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1 "
  },
  {
    "title": "CAMPUS KART ROAD SHOW",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/campus kart.webp"),
    "description": "About the event:\n Campus Kart Clash (CKC), where speed meets engineering finesse!...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day1"
  },
  {
    "title": "BLINK IT",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/blink it.webp"),
    "description": "About the event:\n\n Innovative ideas for start up...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "DASH MASTER:POWER BI CHALLENGE",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/dashmasters.webp"),
    "description": "About the event:\nDashMasters: Power BI Challenge is a hands-on data analytics competition...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },
  {
    "title": "ROBO RACE",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/robo-race.webp"),
    "description": "About the event:\n event that tests participants' ability to think and react...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "Q-FIESTA",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/q fiesta.webp"),
    "description": "About the event:\n Q-Fiesta is an innovative science quiz...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "CUT-2-DESIGN",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/cut 2 design.webp"),
    "description": "About the event:\n Cut2design has the main motto to understand the Machine Drawing...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "CREATE-X",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/create-x.webp"),
    "description": "About the event:\n\nThe objective of CREATE-X is to encourage students to explore creativity...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "CODE-O-LYMPICS",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/code olympics.webp"),
    "description": "About the event:\n\nCode-O-lympics is a fun based coding event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "METAVERSE SPRINT",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/sprint.webp"),
    "description": "About the event:\n event that tests participants' ability to think and react...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day3"
  },
  {
    "title": "TECHNO CRAZY",
    "subtitle": "TECHNICAL",
    "icon": "Power",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/technical/technocrazy.webp"),
    "description": "About the event:\nDashMasters: Power BI Challenge is a hands-on data analytics competition...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "technical",
    "day": "day2"
  },

  /* CULTURAL EVENTS */
  {
    "title": "SAREGA (SOLO SINGING)",
    "subtitle": "CULTURAL",
    "icon": "MicVocal",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/sarega.webp"),
    "description": "About the Event:\nWhat makes your day complete? MUSIC!...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day1"
  },
  {
    "title": "MASTERCHEF (COOKING COMPETITION)",
    "subtitle": "CULTURAL",
    "icon": "ChefHat",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/masterchef.webp"),
    "description": "About the Event:\nAre you ready to don your chef’s hat?...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day1"
  },
  {
    "title": "RAPZAP (SOLO RAP)",
    "subtitle": "CULTURAL",
    "icon": "MicVocal",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/rapzap.webp"),
    "description": "About the Event:\n\nExpressing your thoughts in the form of music is much easier...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day1"
  },
  {
    "title": "ROCKATHON (BATTLE OF BANDS)",
    "subtitle": "CULTURAL",
    "icon": "Drum",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/rockathon.webp"),
    "description": "About the Event:\nThe loudmouth, the screaming, the headbanging are back...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day1"
  },
  {
    "title": "DJ WAR",
    "subtitle": "CULTURAL",
    "icon": "Speaker",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/dj.webp"),
    "description": "About the Event:\n\nGet ready to witness a sonic spectacle...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day1"
  },
  {
    "title": "BEAT THE BEATS ( SOLO INSTRUMENTAL)",
    "subtitle": "CULTURAL",
    "icon": "Guitar",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/beat the beats.webp"),
    "description": "About the Event:\n\nBeat the Beats is a solo event that celebrates the diversity of music...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day2"
  },
  {
    "title": "FOOTLOOSE (SOLO DANCE)",
    "subtitle": "CULTURAL",
    "icon": "Drama",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/footloose.webp"),
    "description": "About the Event:\n\nDance is the expression of one’s soul...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day2"
  },
  {
    "title": "HUNAR (TALENT SHOW)",
    "subtitle": "CULTURAL",
    "icon": "Sparkles",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/hunar.webp"),
    "description": "About the Event:\n\nHunar The Talent Show is a solo event designed to celebrate individuality...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day2"
  },
  {
    "title": "ADAA (FASHION SHOW)",
    "subtitle": "CULTURAL",
    "icon": "Gem",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/adaa.webp"),
    "description": "About the event:\n\nADAA is a platform provided by JECRC to showcase your fashion talent...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day2"
  },
  {
    "title": "NAVRAS (MONO ACT)",
    "subtitle": "CULTURAL",
    "icon": "Drama",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/navras.webp"),
    "description": "About the Event:\n\nMono act is a theatre stage activity where one person performs...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day3"
  },
  {
    "title": "KAVYA (SLAM POETRY)",
    "subtitle": "CULTURAL",
    "icon": "ScrollText",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/kavya.webp"),
    "description": "About the event:\n\nLiberate your thoughts with an open mic...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day3"
  },
  {
    "title": "SHOR BAZZAR (STREET PLAY)",
    "subtitle": "CULTURAL",
    "icon": "Drama",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/shor bazaar.webp"),
    "description": "About the Event:\n\n“Street Play is a mirror, a sharp reflection of the society.”...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day3"
  },
  {
    "title": "BOOTSTRAPPING (Group Dance)",
    "subtitle": "CULTURAL",
    "icon": "Drama",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/bootstraping.webp"),
    "description": "About the Event:\n\nDance is the purest form of expression of all emotions...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day3"
  },
  {
    "title": "BATTLE MANIA (STREET DANCE)",
    "subtitle": "CULTURAL",
    "icon": "Street",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/cultural/battlemania.webp"),
    "description": "About the Event:\n\nThis group event is open to all dance crews...",
    "actionLabel": "REGISTER",
    "onAction": "Connecting to Network...",
    "category": "culture",
    "day": "day3"
  },

  /* SPLASH EVENTS */
  {
    "title": "GULLY CRICKET",
    "subtitle": "SPLASH",
    "icon": "Trophy",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/gully cricket.webp"),
    "description": "About the Event:\n\nGully Cricket is a term used to describe backyard cricket...",
    "actionLabel": "REGISTER",
    "onAction": "Initializing CPU...",
    "category": "splash",
    "day": "day1"
  },
  {
    "title": "BEG BORROW STEEL",
    "subtitle": "SPLASH",
    "icon": "Handshake",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/beg borrow steal.webp"),
    "description": "About the Event:\n\nBeg Borrow Steal is an exciting game...",
    "actionLabel": "REGISTER",
    "onAction": "Initializing CPU...",
    "category": "splash",
    "day": "day3"
  },
  {
    "title": "RELAY RACE",
    "subtitle": "SPLASH",
    "icon": "RotateCcw",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/relay race.webp"),
    "description": "A relay race is a racing competition...",
    "actionLabel": "REGISTER",
    "onAction": "Initializing CPU...",
    "category": "splash",
    "day": "day2"
  },
  {
    "title": "IPL AUCTION",
    "subtitle": "SPLASH",
    "icon": "Trophy",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/ipl auction.webp"),
    "description": "About the Event:\n\nCricket is an emotion...",
    "actionLabel": "REGISTER",
    "onAction": "Initializing CPU...",
    "category": "splash",
    "day": "day1"
  },
  {
    "title": "ARM WRESTLING",
    "subtitle": "SPLASH",
    "icon": "BicepsFlexed",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/arm wrestling.webp"),
    "description": "About the Event:\n\nAn Arm Wrestling event is a thrilling competition...",
    "onAction": "Initializing CPU...",
    "actionLabel": "REGISTER",
    "category": "splash",
    "day": "day2"
  },
  {
    "title": "GAME OF CINEMA",
    "subtitle": "SPLASH",
    "icon": "Film",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/game of cinema.webp"),
    "description": "About the Event:\n\nWho isn’t a fan of web series and movies?...",
    "onAction": "Initializing CPU...",
    "actionLabel": "REGISTER",
    "category": "splash",
    "day": "day3"
  },
  {
    "title": "TREASURE HUNT",
    "subtitle": "SPLASH",
    "icon": "PackageSearch",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/treasure hunt.webp"),
    "description": "About the Event:\n\nTreasure Hunt is a thrilling game...",
    "onAction": "Initializing CPU...",
    "actionLabel": "REGISTER",
    "category": "splash",
    "day": "day3"
  },
  {
    "title": "HALF COURT BASKETBALL(3V3)",
    "subtitle": "SPLASH",
    "icon": "Volleyball",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/half court basketball.webp"),
    "description": "About the Event:\n\n3x3 basketball is a variation of basketball...",
    "onAction": "Initializing CPU...",
    "actionLabel": "REGISTER",
    "category": "splash",
    "day": "day2"
  },
  {
    "title": "SAC RACE",
    "subtitle": "SPLASH",
    "icon": "Medal",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/sac race.webp"),
    "description": "About the Event:\n\nParticipants hop and race with enthusiasm...",
    "onAction": "Initializing CPU...",
    "actionLabel": "REGISTER",
    "category": "splash",
    "day": "day2"
  },
  {
    "title": "CHESS",
    "subtitle": "SPLASH",
    "icon": "Crown",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/chess.webp"),
    "description": "About the Event:\n\nSharpen your mind and challenge your friends...",
    "registrationAmount": "Rs 150/-per participant.",
    "category": "splash",
    "actionLabel": "REGISTER",
    "day": "day2"
  },
  {
    "title": "TUG OF WAR",
    "subtitle": "SPLASH",
    "icon": "MoveHorizontal",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/tug of war .webp"),
    "description": "About the Event:\n\nTug of war is a competitive team sport...",
    "category": "splash",
    "actionLabel": "REGISTER",
    "day": "day1"
  },
  {
    "title": "3 LEG RACE",
    "subtitle": "SPLASH",
    "icon": "FlagTriangleRight",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/three leg race.webp"),
    "description": "About the Event:\n\nThe threelegged race is a fun outdoor game...",
    "category": "splash",
    "actionLabel": "REGISTER",
    "day": "day2"
  },
  {
    "title": "Sprint",
    "subtitle": "SPLASH",
    "icon": "Trophy",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/sprint.webp"),
    "description": "About the Event:\n\n Sprint is a track and field running event...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "splash",
    "day": "day1"
  },
  {
    "title": "Lan Gaming",
    "subtitle": "SPLASH",
    "icon": "Trophy",
    "iconColor": "text-cyan-300",
    "image": getAsset("/events/splash/lan gaming.webp"),
    "description": "About the Event:\n Participation certificates will be given to all participants...",
    "actionLabel": "REGISTER",
    "onAction": "Activating Power Grid...",
    "category": "splash",
    "day": "day1"
  }
];