server {
    listen 80;
    server_name _;

    # Point to the `dist` folder inside the `frontend` directory
    root /usr/share/nginx/html/frontend/dist;  
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;  # Ensure client-side routing takes over
    }
}
