import { getAsset } from "../../config";

const itineraryData = {
  "Day 1": [
    { title: "INAUGRAL CEREMONY", content: "Event starts at 09:00 AM - 10:30 AM", location: "A-BLOCK QUADRANGLE", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "SITUATIONAL QUE", content: "Event starts at 09:00 AM- 11:00 AM", location: "D-BLOCK", icon: getAsset("/itinerary/itenary 2.webp") },
    { title: "FILM FLICK", content: "Event starts at 09:00 AM-11:00 AM", location: "CT-18 , CT-3", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "BEAT THE BEATS", content: "Event starts at 09:00 AM - 12:00 PM", location: "A-BLOCK AUDI", icon: getAsset("/itinerary/itenary 4.webp") },
    { title: "3-D MANIA", content: "Event starts at 09:00 AM - 12:00PM", location: "DF-08", icon: getAsset("/itinerary/itenary 5.webp") },
    { title: "TECHPROBE", content: "Event starts at 09:00 AM - 12:00PM", location: "IBM LAB, A-BLOCK", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "PROGRAMMER'S PLAYGROUND", content: "Event starts at 09:00 AM - 12:00PM", location: "D-BLOCK", icon: getAsset("/itinerary/itenary 7.webp") },
    { title: "SPRINT", content: "Event starts at 09:00 AM- 12:00 PM", location: "A BLOCK LAWN", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "SAREGA(Prelims)", content: "Event starts at 09:00 AM - 12:00 PM", location: "C-BLOCK SEMINAR HALL", icon: getAsset("/itinerary/itenary 19.webp") },
    { title: "GULLY CRICKET", content: "Event starts at 09:00 AM -01:00 PM", location: "A-BLOCK LAWN", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "STAGE PLAY", content: "Event starts at 09:00 AM - 1:00 PM", location: "D-BLOCK AUDI", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "CHESS", content: "Event starts at 09:00 AM-02:00 PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 10.webp") },
    { title: "LAN GAMING", content: "Event starts at 09:00 AM-02:00 PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 11.webp") },
    { title: "ROBO WAR", content: "Event starts at 09:00 AM -06:00 PM", location: "CENTRAL LAWN", icon: getAsset("/itinerary/itenary 12.webp") },
    { title: "NATIONAL PROJECT EXPO", content: "Event starts at 09:00 AM - 06:00 PM", location: "CENTRAL LAWN", icon: getAsset("/itinerary/itenary 13.webp") },
    { title: "BASKET BALL", content: "Event starts at 10:00 AM -02:00 PM", location: "BASKET BALL COURT", icon: getAsset("/itinerary/itenary 11.webp") },
    { title: "CAMPUS KART ROAD SHOW", content: "Event starts at 11:00 AM-01:00 PM", location: "B-BLOCK TO C-BLOCK ROAD", icon: getAsset("/itinerary/itenary 16.webp") },
    { title: "DEXTERITY", content: "Event starts at 11:00 AM-02:00 PM", location: "GROUND FLOOR CORRIDOR", icon: getAsset("/itinerary/itenary 17.webp") },
    { title: "TECH HUNT", content: "Event starts at 12:00PM -03:00 PM", location: "B-BLOCK , BLG-13", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "SAREGA(finals)", content: "Event starts at 01:00 PM -03:00 PM", location: "A-BLOCK AUDI", icon: getAsset("/itinerary/itenary 19.webp") },
    { title: "PUZZLE MANIA", content: "Event starts at 01:00 PM -03:00 PM", location: "IBM LAB, A-BLOCK", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "THREE LEG RACE", content: "Event starts at 01:00 PM-03:00 PM", location: "A BLOCK LAWN", icon: getAsset("/itinerary/itenary 2.webp") },
    { title: "SAC RACE", content: "Event starts at 01:00 PM- 03:00 PM", location: "A BLOCK LAWN", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "TECHNICAL POSTER MAKING COMPETITION", content: "Event starts at 01:00 PM- 04:00 PM", location: "BLG-6", icon: getAsset("/itinerary/itenary 4.webp") },
    { title: "BATTLE OF BRAINS", content: "Event starts at 01:00 PM- 04:00 PM", location: "D-BLOCK (IMPLIED)", icon: getAsset("/itinerary/itenary 5.webp") },
    { title: "ROCKATHON", content: "Event starts at 02:00 PM -05:30 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "DJ WAR", content: "Event starts at 06:00PM -08:30 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 7.webp") },
    { title: "GUEST DJ", content: "Event starts at 08:30PM- 10:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 8.webp") },
  ],

  "Day 2": [
    { title: "STAGE PLAY", content: "Event starts at 8:00 AM - 1:00 PM", location: "D-BLOCK AUDI", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "DASH MASTERS: POWER BI CHALLENGE", content: "Event starts at 09:00 AM - 11:00 AM", location: "BLG 08, B-BLOCK", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "RESIN O'CLOCK", content: "Event starts at 09:00 AM -11:00 AM", location: "DG-04", icon: getAsset("/itinerary/itenary 2.webp") },
    { title: "BLINKIT", content: "Event starts at 09:00 AM-12:00 PM", location: "SEMINAR HALL CS-01", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "DSA BATTLE GROUND", content: "Event starts at 09:00 AM-12:00 PM", location: "GROUND", icon: getAsset("/itinerary/itenary 4.webp") },
    { title: "KNOWLEDGE KNOCKOUT", content: "Event starts at 09:00 AM-12:00 PM", location: "SEMINAR HALL -501", icon: getAsset("/itinerary/itenary 5.webp") },
    { title: "GULLY CRICKET", content: "Event starts at 09:00 AM-12:30 PM", location: "A-BLOCK LAWN", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "LAN GAMING", content: "Event starts at 09:00 AM - 02:00 PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 9.webp") },
    { title: "CHESS", content: "Event starts at 09:00 AM - 02:00PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 10.webp") },
    { title: "ROBO SOCCER", content: "Event starts at 09:00 AM-06:00 PM", location: "CENTRAL LAWN", icon: getAsset("/itinerary/itenary 11.webp") },
    { title: "CAD DARSHAN", content: "Event starts at 10:00 AM- 01:00 PM", location: "CP19,20", icon: getAsset("/itinerary/itenary 12.webp") },
    { title: "CREATIVE PIXELS", content: "Event starts at 10:00 AM- 01:00 PM", location: "IBM LAB, A-BLOCK", icon: getAsset("/itinerary/itenary 13.webp") },
    { title: "KAVYA", content: "Event starts at 10:00 AM- 02:00 PM", location: "A-BLOCK AUDI", icon: getAsset("/itinerary/itenary 17.webp") },
    { title: "BASKETBALL", content: "Event starts at 10:00 AM - 02:00 PM", location: "BASKETBALL COURT", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "FOOTLOOSE", content: "Event starts at 10:00 AM - 02:00 PM", location: "A-BLOCK QUADRANGLE", icon: getAsset("/itinerary/itenary 16.webp") },
    { title: "ARM WRESTLING", content: "Event starts at 11:00 AM - 01:00 PM", location: "D BLOCK GROUND FLOOR", icon: getAsset("/itinerary/itenary 17.webp") },
    { title: "TECHNOCRAZY", content: "Event starts at 11:00 AM -01:00 PM", location: "BLG-14", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "HARDWARE BITES", content: "Event starts at 11:00 AM - 02:00 PM", location: "B-BLOCK TOP FLOOR PREMISES", icon: getAsset("/itinerary/itenary 19.webp") },
    { title: "SCREEN FLEX EVENT", content: "Event starts at 11:00 AM - 02:00 PM", location: "D-BLOCK", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "SLOWEST ROLLER COASTER", content: "Event starts at 11:00 AM - 03:00 PM", location: "C-BLOCK GROUND FLOOR CORRIDOR", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "BEG BORROW STEAL", content: "Event starts at 12:00 PM- 01:00 PM", location: "C BLOCK GROUND FLOOR", icon: getAsset("/itinerary/itenary 2.webp") },
    { title: "BRAIN QUEST", content: "Event starts at 12:00 PM- 02:00 PM", location: "DT-01", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "OWN-IT", content: "Event starts at 12:00 PM- 05:00 PM", location: "D-BLOCK", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "TUG OF WAR", content: "Event starts at 12:30 PM- 03:00 PM", location: "A-BLOCK LAWN", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "HUNAR", content: "Event starts at 1:00 PM-05:00 PM", location: "D-BLOCK AUDI", icon: getAsset("/itinerary/itenary 7.webp") },
    { title: "BATTLEMANIA", content: "Event starts at 02:00 PM - 05:00 PM", location: "A-BLOCK QUADRANGLE", icon: getAsset("/itinerary/itenary 4.webp") },
    { title: "ADAA", content: "Event starts at 05:00 PM-08:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 5.webp") },
    { title: "GUEST BAND", content: "Event starts at 08:00 PM- 10:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 6.webp") },
  ],

  "Day 3": [
    { title: "RELAY RACE", content: "Event starts at 09:00 AM- 11:00 AM", location: "A BLOCK LAWN", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "NAVRAS", content: "Event starts at 09:00 AM- 12:00 PM", location: "A-BLOCK AUDI", icon: getAsset("/itinerary/itenary 2.webp") },
    { title: "BEST OUT OF WASTE", content: "Event starts at 09:00 AM- 12:00 PM", location: "GROUND FLOOR CORRIDOR C-BLOCK", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "TECH SPECTRUM", content: "Event starts at 09:00 AM- 12:00 PM", location: "D-BLOCK", icon: getAsset("/itinerary/itenary 4.webp") },
    { title: "CUT-2-DESIGN", content: "Event starts at 09:00 AM- 12:00 PM", location: "DS-06", icon: getAsset("/itinerary/itenary 5.webp") },
    { title: "GAME OF DRONES", content: "Event starts at 09:00 AM- 05:00 PM", location: "CENTRAL LAWN", icon: getAsset("/itinerary/itenary 6.webp") },
    { title: "ROBO RACE", content: "Event starts at 09:00 AM- 05:00 PM", location: "CENTRAL LAWN", icon: getAsset("/itinerary/itenary 7.webp") },
    { title: "TREASURE HUNT", content: "Event starts at 10:00 AM - 11:00 AM", location: "D BLOCK GROUND FLOOR", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "CREATE-X", content: "Event starts at 10:00 AM - 12:00 PM", location: "CT-18,CT-03", icon: getAsset("/itinerary/itenary 9.webp") },
    { title: "SUBITO", content: "Event starts at 10:00 AM - 01:00 PM", location: "DF0-8, D-BLOCK", icon: getAsset("/itinerary/itenary 10.webp") },
    { title: "ELECTROQUIZZER", content: "Event starts at 10:00 AM - 01:00 PM", location: "BLG-06", icon: getAsset("/itinerary/itenary 11.webp") },
    { title: "ARM WRESTLING", content: "Event starts at 10:00 AM- 01:00 PM", location: "D BLOCK GROUND FLOOR", icon: getAsset("/itinerary/itenary 12.webp") },
    { title: "RAPZAP(prelims)", content: "Event starts at 10:00 AM - 01:00 PM", location: "C-BLOCK OVAL GARDEN", icon: getAsset("/itinerary/itenary 19.webp") },
    { title: "CODE-O-LYMPICS", content: "Event starts at 11:00 AM- 01:00 PM", location: "IBM LAB, A-BLOCK", icon: getAsset("/itinerary/itenary 13.webp") },
    { title: "TUG OF WAR", content: "Event starts at 11:00 AM- 02:00 PM", location: "A BLOCK LAWN", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "METAVERSE SPRINT", content: "Event starts at 11:00 AM- 03:00 PM", location: "D-BLOCK CLASSROOM", icon: getAsset("/itinerary/itenary 17.webp") },
    { title: "IPL AUCTION", content: "Event starts at 12:00 PM -02:00 PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 8.webp") },
    { title: "GAME OF CINEMA", content: "Event starts at 12:00 PM - 02:00 PM", location: "SEMINAR HALL", icon: getAsset("/itinerary/itenary 16.webp") },
    { title: "Q-FIESTA", content: "Event starts at 12:00 PM - 03:00 PM", location: "SEMINAR HALL - 401", icon: getAsset("/itinerary/itenary 17.webp") },
    { title: "SHOR BAZZAR", content: "Event starts at 01:00 PM - 03:00 PM", location: "A-BLOCK QUADRANGLE", icon: getAsset("/itinerary/itenary 18.webp") },
    { title: "RAPZAP(finals)", content: "Event starts at 03:00 PM-04:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 19.webp") },
    { title: "BOOTSTRAPPING", content: "Event starts at 05:00 PM-08:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 1.webp") },
    { title: "CELEBRITY NIGHT", content: "Event starts at 08:00 PM-10:00 PM", location: "MAIN STAGE", icon: getAsset("/itinerary/itenary 2.webp") },
  ],
};

export default itineraryData;
